Changed test env directory from /tmp to /tmp/pt-test

diff --git a/sandbox/start-sandbox b/sandbox/start-sandbox
--- a/sandbox/start-sandbox
+++ b/sandbox/start-sandbox
@@ -2,7 +2,7 @@
 
 # This script starts a Percona Toolkit sandbox sever.  sandbox/test-env
 # uses it, and many tests use it to create special, temporary sandbox
-# servers.  The actual startup is done by /tmp/PORT/start, which this
+# servers.  The actual startup is done by /tmp/pt-test/PORT/start, which this
 # script calls after doing a bunch of sanity checks.
 #
 # Exit 0 if the sandbox server started ok, else 1 and debug_sandbox()
@@ -18,12 +18,12 @@ debug_sandbox() {
    set -x
    local port="$1"
    ps x | grep mysql >&2
-   if [ -d "/tmp/$port" ]; then
-      ls -lh /tmp/$port/* >&2
-      cat /tmp/$port/data/mysqld.log >&2
-      tail -n 100 /tmp/$port/data/genlog >&2
+   if [ -d "/tmp/pt-test/$port" ]; then
+      ls -lh /tmp/pt-test/$port/* >&2
+      cat /tmp/pt-test/$port/data/mysqld.log >&2
+      tail -n 100 /tmp/pt-test/$port/data/genlog >&2
    else
-      echo "/tmp/$port does not exist" >&2
+      echo "/tmp/pt-test/$port does not exist" >&2
    fi
 }
 
@@ -36,21 +36,21 @@ mysql_upgrade_on() {
 
 make_sandbox() {
    # Make the sandbox dir and extract the base files.
-   rm -rf /tmp/$port || die "Failed to rm /tmp/$port"
-   mkdir /tmp/$port  || die "Failed to mkdir /tmp/$port"
-   cp $PERCONA_TOOLKIT_BRANCH/sandbox/servers/${APP#mysql}/$version/my.sandbox.cnf /tmp/$port
+   rm -rf /tmp/pt-test/$port || die "Failed to rm /tmp/pt-test/$port"
+   mkdir /tmp/pt-test/$port  || die "Failed to mkdir /tmp/pt-test/$port"
+   cp $PERCONA_TOOLKIT_BRANCH/sandbox/servers/${APP#mysql}/$version/my.sandbox.cnf /tmp/pt-test/$port
    if [ -e $PERCONA_TOOLKIT_BRANCH/sandbox/servers/${APP#mysql}/$version/data.tar.gz ]; then
-      tar xzf $PERCONA_TOOLKIT_BRANCH/sandbox/servers/${APP#mysql}/$version/data.tar.gz -C /tmp/$port
+      tar xzf $PERCONA_TOOLKIT_BRANCH/sandbox/servers/${APP#mysql}/$version/data.tar.gz -C /tmp/pt-test/$port
    fi
 
    for script in "$PERCONA_TOOLKIT_BRANCH/sandbox/servers/"*; do
       if [ -f $script ]; then
-        cp $script /tmp/$port
+        cp $script /tmp/pt-test/$port
       fi
    done
 
    if [ "${type}" = "cluster" ]; then
-      cp $PERCONA_TOOLKIT_BRANCH/sandbox/servers/pxc/$version/my.sandbox.cnf /tmp/$port
+      cp $PERCONA_TOOLKIT_BRANCH/sandbox/servers/pxc/$version/my.sandbox.cnf /tmp/pt-test/$port
 
       local libgalera="$PERCONA_TOOLKIT_SANDBOX/lib/libgalera_smm.so"
       local cluster_name="${CLUSTER_NAME:-"pt_sandbox_cluster"}"
@@ -63,80 +63,80 @@ make_sandbox() {
 
          local this_listen_port=$(($port + 10))
          local this_cluster_address="gcomm://$ip:$this_listen_port"
-         sed -e "s!gcomm://\$!$this_cluster_address!g" -i.bak "/tmp/$master_port/my.sandbox.cnf"
+         sed -e "s!gcomm://\$!$this_cluster_address!g" -i.bak "/tmp/pt-test/$master_port/my.sandbox.cnf"
       fi
 
-      sed -e "s/ADDR/$ip/g" -i.bak "/tmp/$port/my.sandbox.cnf"
-      sed -e "s!CLUSTER_AD!$cluster_address!g" -i.bak "/tmp/$port/my.sandbox.cnf"
-      sed -e "s/CLUSTER_NAME/$cluster_name/g" -i.bak "/tmp/$port/my.sandbox.cnf"
-      sed -e "s/RECEIVE_PRT/$receive_port/g" -i.bak "/tmp/$port/my.sandbox.cnf"
-      sed -e "s/LISTEN_PRT/$listen_port/g" -i.bak "/tmp/$port/my.sandbox.cnf"
-      sed -e "s!LIBGALERA!$libgalera!g" -i.bak "/tmp/$port/my.sandbox.cnf"
+      sed -e "s/ADDR/$ip/g" -i.bak "/tmp/pt-test/$port/my.sandbox.cnf"
+      sed -e "s!CLUSTER_AD!$cluster_address!g" -i.bak "/tmp/pt-test/$port/my.sandbox.cnf"
+      sed -e "s/CLUSTER_NAME/$cluster_name/g" -i.bak "/tmp/pt-test/$port/my.sandbox.cnf"
+      sed -e "s/RECEIVE_PRT/$receive_port/g" -i.bak "/tmp/pt-test/$port/my.sandbox.cnf"
+      sed -e "s/LISTEN_PRT/$listen_port/g" -i.bak "/tmp/pt-test/$port/my.sandbox.cnf"
+      sed -e "s!LIBGALERA!$libgalera!g" -i.bak "/tmp/pt-test/$port/my.sandbox.cnf"
    fi
 
-   for file in `grep -l PORT /tmp/$port/* 2>/dev/null`; do
+   for file in `grep -l PORT /tmp/pt-test/$port/* 2>/dev/null`; do
       sed -e "s/PORT/$port/g" -i.bak $file
       # Use ! instead of / because the replacment has / (it's a directory)
       sed -e "s!PERCONA_TOOLKIT_SANDBOX!$PERCONA_TOOLKIT_SANDBOX!g" -i.bak $file
       sed -e "s!MYSQLD!$mysqld!g" -i.bak $file
    done
-   rm /tmp/$port/*.bak >/dev/null 2>&1
+   rm /tmp/pt-test/$port/*.bak >/dev/null 2>&1
 
    if [ -n "$BINLOG_FORMAT" ]; then
-      echo "binlog-format=$BINLOG_FORMAT" >> /tmp/$port/my.sandbox.cnf
+      echo "binlog-format=$BINLOG_FORMAT" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
    if [ -n "$SLAVE_EXEC_MODE" ]; then
-      echo "slave_exec_mode=$SLAVE_EXEC_MODE" >> /tmp/$port/my.sandbox.cnf
+      echo "slave_exec_mode=$SLAVE_EXEC_MODE" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
    if [ -n "$SQL_MODE" ]; then
-      echo "sql-mode=$SQL_MODE" >> /tmp/$port/my.sandbox.cnf
+      echo "sql-mode=$SQL_MODE" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
    if [ -n "$GENLOG" ]; then
-      echo "log=genlog" >> /tmp/$port/my.sandbox.cnf
+      echo "log=genlog" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
    if [ -n "$SKIP_INNODB" ]; then
-      echo "skip-innodb" >> /tmp/$port/my.sandbox.cnf
-      echo "default-storage-engine=myisam" >> /tmp/$port/my.sandbox.cnf
+      echo "skip-innodb" >> /tmp/pt-test/$port/my.sandbox.cnf
+      echo "default-storage-engine=myisam" >> /tmp/pt-test/$port/my.sandbox.cnf
       if [ "$version" ">" "5.5" ]; then
-         echo "default-tmp-storage-engine=myisam" >> /tmp/$port/my.sandbox.cnf
+         echo "default-tmp-storage-engine=myisam" >> /tmp/pt-test/$port/my.sandbox.cnf
       fi
    fi
    if [ -n "$MODE_ANSI" ]; then
-      echo "sql_mode=ansi" >> /tmp/$port/my.sandbox.cnf
+      echo "sql_mode=ansi" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
    if [ -n "$MULTIPLE_BUFFER_POOLS" ]; then
-      echo "innodb_buffer_pool_instances=$MULTIPLE_BUFFER_POOLS" >> /tmp/$port/my.sandbox.cnf
+      echo "innodb_buffer_pool_instances=$MULTIPLE_BUFFER_POOLS" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
    if [ -n "$LOCAL_INFILE" ]; then
-      echo "local-infile=$LOCAL_INFILE" >> /tmp/$port/my.sandbox.cnf
+      echo "local-infile=$LOCAL_INFILE" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
    if [ -n "$QUERY_CACHE_SIZE" ]; then
-      echo "query_cache_type=1" >> /tmp/$port/my.sandbox.cnf
-      echo "query_cache_size=$QUERY_CACHE_SIZE" >> /tmp/$port/my.sandbox.cnf
+      echo "query_cache_type=1" >> /tmp/pt-test/$port/my.sandbox.cnf
+      echo "query_cache_size=$QUERY_CACHE_SIZE" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
 
    if [ -n "$GTID" ]; then
-      echo "gtid_mode=on" >> /tmp/$port/my.sandbox.cnf
-      echo "enforce_gtid_consistency" >> /tmp/$port/my.sandbox.cnf
+      echo "gtid_mode=on" >> /tmp/pt-test/$port/my.sandbox.cnf
+      echo "enforce_gtid_consistency" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
    if [ -n "$REPLICATION_THREADS" ]; then
-      echo "slave_parallel_workers=$REPLICATION_THREADS" >> /tmp/$port/my.sandbox.cnf
+      echo "slave_parallel_workers=$REPLICATION_THREADS" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
 
    if [ -n "$EXTRA_DEFAULTS_FILE" ]; then
-      cat "$EXTRA_DEFAULTS_FILE" >> /tmp/$port/my.sandbox.cnf
+      cat "$EXTRA_DEFAULTS_FILE" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
 
    # If the sandbox is a slave, set it read_only.
    if [ "$type" = "slave" ]; then
-      echo "read_only" >> /tmp/$port/my.sandbox.cnf
+      echo "read_only" >> /tmp/pt-test/$port/my.sandbox.cnf
    fi
 
    # Start the sandbox and check that it has InnoDB.
-   /tmp/$port/start
+   /tmp/pt-test/$port/start
    if [ $? -eq 0 ]; then
       if [ -z "$SKIP_INNODB" ]; then
-         /tmp/$port/use -e 'SHOW /*!40100 ENGINE*/ INNODB STATUS' | grep 'INNODB MONITOR OUTPUT' >/dev/null 2>&1
+         /tmp/pt-test/$port/use -e 'SHOW /*!40100 ENGINE*/ INNODB STATUS' | grep 'INNODB MONITOR OUTPUT' >/dev/null 2>&1
          # grep exits 0 if lines are found
          if [ $? -ne 0 ]; then
             echo "Sandbox $type $port doesn't have InnoDB." >&2
@@ -145,7 +145,7 @@ make_sandbox() {
          fi
 
          for sql in "$PERCONA_TOOLKIT_BRANCH/sandbox/servers/${APP#mysql}/$version/"*.sql; do
-            [ -f "$sql" ] && /tmp/$port/use < $sql
+            [ -f "$sql" ] && /tmp/pt-test/$port/use < $sql
          done
       fi
 
@@ -153,7 +153,7 @@ make_sandbox() {
       if [ -n "$SYS_SCHEMA" ]; then
          local sys_dir="$PERCONA_TOOLKIT_BRANCH/sandbox/servers/${APP#mysql}/$version/sys"
          cd "$sys_dir"
-         [ -f "$sys_dir/sys.sql" ] && /tmp/$port/use < "$sys_dir/sys.sql"
+         [ -f "$sys_dir/sys.sql" ] && /tmp/pt-test/$port/use < "$sys_dir/sys.sql"
       fi
    else
       echo "Sandbox $type $port failed to start." >&2
@@ -161,17 +161,17 @@ make_sandbox() {
       exit 1
    fi
 
-   /tmp/$port/use -e "CREATE DATABASE IF NOT EXISTS percona_test";
-   /tmp/$port/use -e "CREATE TABLE IF NOT EXISTS percona_test.sentinel (id INT PRIMARY KEY, ping VARCHAR(64) NOT NULL DEFAULT '')";
+   /tmp/pt-test/$port/use -e "CREATE DATABASE IF NOT EXISTS percona_test";
+   /tmp/pt-test/$port/use -e "CREATE TABLE IF NOT EXISTS percona_test.sentinel (id INT PRIMARY KEY, ping VARCHAR(64) NOT NULL DEFAULT '')";
 
    if [ -n "${MYSQL_UPGRADE:-""}" ]; then
-      mysql_upgrade_on /tmp/$port/my.sandbox.cnf
+      mysql_upgrade_on /tmp/pt-test/$port/my.sandbox.cnf
    fi
 
    # If the sandbox is a slave, start the slave.
    if [ "$type" = "slave" ]; then
-      /tmp/$port/use -e "change master to master_host='127.0.0.1', master_user='msandbox', master_password='msandbox', master_port=$master_port"
-      /tmp/$port/use -e "start slave"
+      /tmp/pt-test/$port/use -e "change master to master_host='127.0.0.1', master_user='msandbox', master_password='msandbox', master_port=$master_port"
+      /tmp/pt-test/$port/use -e "start slave"
    fi
 
    return 0
@@ -202,8 +202,8 @@ fi
 
 # If creating a slave, the master must exist first.  Not true for creating
 # a master-master though.
-if [ "$type" = "slave" ] && [ ! -d "/tmp/$master_port" ]; then
-   die "Master sandbox does not exist: /tmp/$master_port"
+if [ "$type" = "slave" ] && [ ! -d "/tmp/pt-test/$master_port" ]; then
+   die "Master sandbox does not exist: /tmp/pt-test/$master_port"
 fi
 
 # ###########################################################################
@@ -263,7 +263,7 @@ fi
 # ###########################################################################
 # Start and configure the sandbox server.
 # ###########################################################################
-PIDFILE="/tmp/$port/data/mysql_sandbox$port.pid"
+PIDFILE="/tmp/pt-test/$port/data/mysql_sandbox$port.pid"
 
 if [ -f $PIDFILE ]; then
    echo "Sandbox $port already started (found pid file $PIDFILE)"
@@ -280,12 +280,12 @@ else
       make_sandbox
 
       # Slave mm2 -> mm1
-      /tmp/$mm2_port/use -e "change master to master_host='127.0.0.1', master_log_file='mysql-bin.000001', master_log_pos=0, master_user='msandbox', master_password='msandbox', master_port=$mm1_port"
-      /tmp/$mm2_port/use -e "start slave"
+      /tmp/pt-test/$mm2_port/use -e "change master to master_host='127.0.0.1', master_log_file='mysql-bin.000001', master_log_pos=0, master_user='msandbox', master_password='msandbox', master_port=$mm1_port"
+      /tmp/pt-test/$mm2_port/use -e "start slave"
 
       # Slave mm1 -> mm2
-      /tmp/$mm1_port/use -e "change master to master_host='127.0.0.1', master_log_file='mysql-bin.000001', master_log_pos=0, master_user='msandbox', master_password='msandbox', master_port=$mm2_port"
-      /tmp/$mm1_port/use -e "start slave"
+      /tmp/pt-test/$mm1_port/use -e "change master to master_host='127.0.0.1', master_log_file='mysql-bin.000001', master_log_pos=0, master_user='msandbox', master_password='msandbox', master_port=$mm2_port"
+      /tmp/pt-test/$mm1_port/use -e "start slave"
    fi
 fi
 
diff --git a/sandbox/stop-sandbox b/sandbox/stop-sandbox
--- a/sandbox/stop-sandbox
+++ b/sandbox/stop-sandbox
@@ -12,20 +12,20 @@ fi
 exit_status=0
 
 for port in "$@"; do
-   if ! [ -d "/tmp/$port" ]; then
+   if ! [ -d "/tmp/pt-test/$port" ]; then
       echo "MySQL test server on port $port does not exist."
       continue
    fi
 
-   if [ -x "/tmp/$port/stop" ]; then
-      /tmp/$port/stop
+   if [ -x "/tmp/pt-test/$port/stop" ]; then
+      /tmp/pt-test/$port/stop
       exit_status=$((exit_status | $?))
    else
-      echo "/tmp/$port is missing files:" >&2
-      ls -la /tmp/$port >&2
+      echo "/tmp/pt-test/$port is missing files:" >&2
+      ls -la /tmp/pt-test/$port >&2
    fi
 
-   rm -rf /tmp/$port
+   rm -rf /tmp/pt-test/$port
    exit_status=$((exit_status | $?))
 done
 
